/bin/sh -c set -eux;
savedAptMark="$(apt-mark showmanual)";
 	if ! command -v gpg > /dev/null;
      then 		apt-get update; 
        apt-get install -y --no-install-recommends 			gnupg 			dirmngr 		; 		
        rm -rf /var/lib/apt/lists/*; 	fi; 	
        dpkgArch="$(dpkg --print-architecture)"; 
            case "${dpkgArch##*-}" in 	amd64) tarArch='x86_64'; 
            dirArch='x64'; 
            sha256='80dec351d1a593e8ad152636971a48d0c81bfcfab92c87f3604663616f1e8bc5' ;; 		arm64) tarArch='aarch64';
            dirArch='aarch64'; 
            sha256='7ffdf6358d6c2b8a53757e517998d55833c363d4730c9452ddd44b223f10333a' ;; 		i386) tarArch='i686'; 
            dirArch='x86'; 
            sha256='70f7327a26dd2dda87eb6cdf99269f974ae722a02c54b2faa174ceda125bf006' ;; 		*) echo >&2 "error: current architecture ($dpkgArch) does not have a corresponding Julia binary release"; 
            exit 1 ;; 	esac; 
            folder="$(echo "$JULIA_VERSION" | cut -d. -f1-2)"; 
            curl -fL -o julia.tar.gz.asc "https://julialang-s3.julialang.org/bin/linux/${dirArch}/${folder}/julia-${JULIA_VERSION}-linux-${tarArch}.tar.gz.asc"; 
            curl -fL -o julia.tar.gz     "https://julialang-s3.julialang.org/bin/linux/${dirArch}/${folder}/julia-${JULIA_VERSION}-linux-${tarArch}.tar.gz"; 	
            echo "${sha256} *julia.tar.gz" | sha256sum -c -; 
            export GNUPGHOME="$(mktemp -d)"; 
                gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$JULIA_GPG"; 
                gpg --batch --verify julia.tar.gz.asc julia.tar.gz; 	
                command -v gpgconf > /dev/null && gpgconf --kill all; 	]
                rm -rf "$GNUPGHOME" julia.tar.gz.asc; 		
                mkdir "$JULIA_PATH"; 	
                tar -xzf julia.tar.gz -C "$JULIA_PATH" --strip-components 1; 	
                rm julia.tar.gz; 		
                apt-mark auto '.*' > /dev/null; 	
                [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; 	
                apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false;
                        julia --version